# settings shared between the lib and the users of KDSingleApplication

DEFINES +=\
    QT_USE_STRINGBUILDER \
    QT_NO_CAST_FROM_ASCII \
    QT_NO_CAST_TO_ASCII \
    QT_DISABLE_DEPRECATED_BEFORE=0x051200 \
    QT_DEPRECATED_WARNINGS \

CONFIG += c++14

DEFINES += KDSINGLEAPPLICATION_STATIC_BUILD
